#!/usr/bin/env bash

if [ -z "$1" ]; then
    echo "Error: No wallpaper path provided"
    echo "Usage: $0 <wallpaper_path>"
    exit 1
fi

if ! ps aux | rg "swww" > /dev/null; then
    swww-daemon &
    # Wait a bit for daemon to initialize
    sleep 0.5
fi

swww img "$1" --resize crop --filter Nearest
