#!/usr/bin/env bash

if [ -z "$1" ]; then
    echo "Error: No wallpaper path provided"
    echo "Usage: $0 <wallpaper_path>"
    exit 1
fi

awww-daemon & sleep 0.5

awww img "$1" --resize crop --filter Nearest
