#!/usr/bin/env bash

if [ -z "$1" ]; then
    echo "Error: No wallpaper path provided"
    echo "Usage: $0 <wallpaper_path>"
    exit 1
fi

swww-daemon & sleep 0.5

swww img "$1" --resize crop --filter Nearest
